name: Lint and Test
inputs:
  SA_PASSWORD:
    required: true
    default: abcdefgh1!
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
      with:
        node-version: '16'
        check-latest: true
        registry-url: 'https://www.myget.org/F/ed-fi/npm/'

    - name: Install
      run: yarn install
      shell: bash

    - name: Lint
      run: yarn test:lint
      shell: bash

    - name: Start Docker for SQL Server
      run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=${{ inputs.SA_PASSWORD }}' -e 'MSSQL_PID=Express' -p 1433:1433 --name mssql -d mcr.microsoft.com/mssql/server:2017-latest
      shell: bash

    - name: Unit tests
      run: yarn test:unit:ci --ci  --config ./jest.ci-config.js
      shell: bash
      env:
        MSSQL_USERNAME: sa
        MSSQL_PASSWORD: ${{ inputs.SA_PASSWORD }}