name: Lint and Test
inputs:
  SA_PASSWORD:
    required: true
    default: abcdefgh1!
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
      with:
        node-version: '16'
        check-latest: true
        registry-url: 'https://www.myget.org/F/ed-fi/npm/'

    - name: Install
      run: yarn install
      shell: bash

    - name: Lint
      run: yarn test:lint
      shell: bash

    - name: Unit tests
      run: yarn test:unit:ci --ci  --config ./jest.ci-config.js
      shell: bash

    - name: Start Docker for SQL Server
      run: |
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=${{ inputs.SA_PASSWORD }}' -e 'MSSQL_PID=Express' -p 1433:1433 \
          --name mssql -d mcr.microsoft.com/mssql/server:2019-latest
      shell: bash

    - name: Create SQL Server Testing Database
      run: |
        docker exec -i mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ inputs.SA_PASSWORD }} -d master \
          -Q "CREATE DATABASE MetaEd_Ods_Integration_Tests"
      shell: bash

    - name: SQLServer Unit tests
      run: yarn test:unit:ods:sqlserver:db --ci  --config ./jest.ci-config.js
      shell: bash
      env:
        MSSQL_USERNAME: sa
        MSSQL_PASSWORD: ${{ inputs.SA_PASSWORD }}
        MSSQL_TRUST_CERTIFICATE: 'true' # This is required for successful auth to the docker SQL Server

    - name: Setup PostgreSQL for testing
      # Postgres on Ubuntu is installed locally but the service needs to be started. The default postgres 
      # super user password is blank, so updating to what the unit tests expect, also creating the testing database
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres psql -U postgres -c "create database metaed_integration_tests;"
        sudo -u postgres psql -U postgres -c "alter user postgres with password 'docker';"
      shell: bash

    - name: PostgreSQL Unit tests
      run: yarn test:unit:ods:postgresql:db --ci --config ./jest.ci-config.js
      shell: bash